### ISSUE TITLE
Getting an API key

### ISSUE THREAD

**Issue by SevereOverfl0w** [thesephist/frieden#1]
I've created an API key, but for my calendar it's giving "Not found". I used the API explorer and confirmed that the ID is correct.

Do I need to create the API key in a special way?

**Comment by thesephist** [comment]
Hey @SevereOverfl0w, perhaps it's a permissions issue? "Not found" makes me suspect that perhaps you haven't set the calendar free/busy permissions to be viewable to the public (I guess I could have made it private, but was more complicated and didn't feel it was necessary).

**Comment by SevereOverfl0w** [comment]
Ah, I haven't made it public.  I did foolishly miss that step 😁.  Thanks!
